"""Initial schema

Revision ID: 447559806219
Revises: 
Create Date: 2026-07-16 14:02:34.929351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447559806219'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('corporate_account_id', sa.UUID(), nullable=True))
    op.add_column('hospitals', sa.Column('hospital_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hospitals_corporate_account_id'), 'hospitals', ['corporate_account_id'], unique=False)
    op.create_index(op.f('ix_hospitals_hospital_group_id'), 'hospitals', ['hospital_group_id'], unique=False)
    op.create_foreign_key(None, 'hospitals', 'corporate_accounts', ['corporate_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hospitals', 'hospital_groups', ['hospital_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_index(op.f('ix_hospitals_hospital_group_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_corporate_account_id'), table_name='hospitals')
    op.drop_column('hospitals', 'hospital_group_id')
    op.drop_column('hospitals', 'corporate_account_id')
    # ### end Alembic commands ###
